name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 6 * * *" # daily at 6am UTC

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg?color_snake=%236E8B74&color_dots=%23111827,%23334155,%236B8FB3,%236E8B74,%2394A3B8

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
